---
# ssh_authorized_keys: []

debian:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nfs-common
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
